remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

author:
  name: "Matt Bernstein"
  avatar: "/assets/images/matt.jpg"   # put your headshot here
  bio: "M.S. Data Science @ UConn â€¢ ML, analytics, and data products."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:mbernstein663@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/matthew-bernstein-3a3977227/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mbernstein663"
